# Generated by Django 3.2 on 2022-12-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221210_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
