# Generated by Django 3.2.16 on 2022-12-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
